# Generates the pages that come from the package sources:
#   - reference/*.qmd from man/*.Rd
#   - news.qmd from NEWS.md
#   - images/readme_*.png from man/figures (the site logo is images/logo.png)
# Run automatically by `quarto render` (pre-render step). The package
# sources are read from the parent folder (the package root), or from
# FOOTBAYES_PKG if set.

pkg <- Sys.getenv("FOOTBAYES_PKG", "..")
stopifnot(file.exists(file.path(pkg, "DESCRIPTION")))

generated <- "<!-- Generated by _prerender.R: do not edit by hand. -->"

write_utf8 <- function(lines, path) {
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  writeLines(enc2utf8(lines), path, useBytes = TRUE)
}

read_utf8 <- function(path) readLines(path, encoding = "UTF-8", warn = FALSE)

unescape_html <- function(x) {
  x <- gsub("&lt;", "<", x, fixed = TRUE)
  x <- gsub("&gt;", ">", x, fixed = TRUE)
  x <- gsub("&quot;", "\"", x, fixed = TRUE)
  x <- gsub("&#39;", "'", x, fixed = TRUE)
  gsub("&amp;", "&", x, fixed = TRUE)
}

yaml_string <- function(x) paste0("\"", gsub("\"", "\\\\\"", x), "\"")


# Images ---------------------------------------------------------------

dir.create("images", showWarnings = FALSE)
# The site has its own logo (images/logo.png), so the package logo is not copied
invisible(file.copy(list.files(file.path(pkg, "man", "figures"), pattern = "^readme_", full.names = TRUE),
                    "images", overwrite = TRUE))


# Reference ------------------------------------------------------------

# Topics shown in the reference index, by group. Topics not listed here
# are added to "Other" so that a new Rd file is never left out.
groups <- list(
  "Model fitting" = c("stan_foot", "mle_foot", "btd_foot", "priors"),
  "Abilities and strengths" = c("foot_abilities", "plot_btdPosterior", "plot_logStrength"),
  "Model checking and predictions" = c("pp_foot", "foot_prob", "foot_rank", "foot_round_robin"),
  "Model comparison" = c("compare_foot"),
  "Print methods" = c("print.stanFoot", "print.btdFoot", "print.compareFoot"),
  "Datasets" = c("italy", "england")
)

group_descriptions <- c(
  "Model fitting" = "Fit goal-based models by maximum likelihood or in a Bayesian framework, and estimate team strengths with the Bradley-Terry-Davidson model.",
  "Abilities and strengths" = "Plot the estimated team abilities and strengths.",
  "Model checking and predictions" = "Posterior predictive checks, match probabilities and league table predictions.",
  "Model comparison" = "Compare the predictive performance of fitted models.",
  "Print methods" = "Summaries of the fitted objects.",
  "Datasets" = "Match results of the Italian and English leagues."
)

# Rd -> HTML; the code of the Usage and Examples sections becomes
# highlighted R code blocks, \eqn and \deqn become MathJax math.
rd_to_qmd <- function(rd_file) {
  rd <- tools::parse_Rd(rd_file, encoding = "UTF-8")
  html <- paste(utils::capture.output(
    tools::Rd2HTML(rd, out = "", package = "footBayes", dynamic = FALSE,
                   standalone = FALSE, Links = NULL)
  ), collapse = "\n")

  title <- sub("(?s).*?<h2[^>]*>(.*?)</h2>.*", "\\1", html, perl = TRUE)
  title <- unescape_html(gsub("<[^>]+>", "", title))
  html <- sub("(?s).*?</h2>(<span[^>]*></span>)?", "", html, perl = TRUE)

  html <- gsub("(?s)<p style=\"text-align: center;\"><code class=\"reqn\">(.*?)</code>\\s*</p>",
               "<p><span class=\"math display\">\\\\[\\1\\\\]</span></p>", html, perl = TRUE)
  html <- gsub("(?s)<code class=\"reqn\">(.*?)</code>",
               "<span class=\"math inline\">\\\\(\\1\\\\)</span>", html, perl = TRUE)

  sections <- strsplit(html, "<h3>", fixed = TRUE)[[1]][-1]
  body <- unlist(lapply(sections, function(s) {
    heading <- sub("(?s)</h3>.*", "", s, perl = TRUE)
    content <- sub("(?s).*?</h3>", "", s, perl = TRUE)
    if (heading %in% c("Usage", "Examples")) {
      code <- regmatches(content, gregexpr("(?s)<pre><code[^>]*>.*?</code></pre>", content, perl = TRUE))[[1]]
      code <- unescape_html(gsub("(?s)<pre><code[^>]*>|</code></pre>", "", code, perl = TRUE))
      code <- trimws(code, which = "right")
      c(paste("##", heading), "", unlist(lapply(code, function(x) c("```r", x, "```", ""))))
    } else {
      c(paste("##", heading), "", "```{=html}", trimws(content), "```", "")
    }
  }))

  c("---", paste("title:", yaml_string(title)), "---", "", generated, "", body)
}

dir.create("reference", showWarnings = FALSE)
unlink(list.files("reference", pattern = "\\.qmd$", full.names = TRUE))

rd_files <- list.files(file.path(pkg, "man"), pattern = "\\.Rd$", full.names = TRUE)
topics <- tools::file_path_sans_ext(basename(rd_files))
titles <- character()
labels <- character()

# Exported functions and registered S3 methods, used as the labels of the index
ns <- parseNamespaceFile(basename(normalizePath(pkg)), dirname(normalizePath(pkg)))
exported <- c(ns$exports, paste(ns$S3methods[, 1], ns$S3methods[, 2], sep = "."))

for (i in seq_along(rd_files)) {
  qmd <- rd_to_qmd(rd_files[i])
  rd <- tools::parse_Rd(rd_files[i], encoding = "UTF-8")
  tags <- vapply(rd, function(x) attr(x, "Rd_tag"), "")
  aliases <- vapply(rd[tags == "\\alias"], function(x) as.character(x[[1]]), "")
  is_data <- any(vapply(rd[tags == "\\docType"], function(x) as.character(x[[1]]), "") == "data")
  if (!is_data) aliases <- intersect(aliases, exported)
  labels[topics[i]] <- paste0("`", aliases, if (!is_data) "()", "`", collapse = " ")
  titles[topics[i]] <- sub("^title: \"(.*)\"$", "\\1", qmd[2])
  write_utf8(qmd, file.path("reference", paste0(topics[i], ".qmd")))
}

other <- setdiff(topics, unlist(groups))
if (length(other)) groups[["Other"]] <- other

index <- c("---", "title: \"Functions Reference\"", "---", "", generated, "")
for (g in names(groups)) {
  g_topics <- intersect(groups[[g]], topics)
  if (!length(g_topics)) next
  index <- c(index, paste("##", g), "",
             if (!is.na(group_descriptions[g])) c(group_descriptions[[g]], ""),
             "| | |", "|:--|:--|",
             sprintf("| [%s](%s.qmd) | %s |", labels[g_topics], g_topics,
                     gsub("|", "\\|", titles[g_topics], fixed = TRUE)),
             ': {.fb-ref-index tbl-colwidths="[35,65]"}',
             "")
}
write_utf8(index, "reference/index.qmd")


# News -----------------------------------------------------------------

news <- read_utf8(file.path(pkg, "NEWS.md"))
news <- sub("^# footBayes ", "## footBayes ", news)
news <- sub("^## (?!footBayes)", "### ", news, perl = TRUE)
write_utf8(c("---", "title: \"Changelog\"", "---", "", generated, "", news), "news.qmd")
